const Classes = [
    {
        year: 2025,
        class: "G1H",
        teacher: "田端 毅",
        students:[
            { num: 1, name: "浅井 蒼葉" },
            { num: 2, name: "安藤 聡" },
            { num: 3, name: "飯田 空翔" },
            { num: 4, name: "生田 恭一郎" },
            { num: 5, name: "伊藤 有希" },
            { num: 6, name: "大橋 柚斗" },
            { num: 7, name: "奥村 華澄" },
            { num: 8, name: "加藤 悠真" },
            { num: 9, name: "上島 璃子" },
            { num: 10, name: "川村 翔" },
            { num: 11, name: "木村 心和" },
            { num: 12, name: "久郷 藍子" },
            { num: 13, name: "小出 愛実" },
            { num: 14, name: "小牧 璃子" },
            { num: 15, name: "斉藤 みなみ" },
            { num: 16, name: "塩谷 愛月" },
            { num: 17, name: "澁谷 陽歩" },
            { num: 18, name: "杉本 イアン" },
            { num: 19, name: "鈴木 康介" },
            { num: 20, name: "曽我部 隼人" },
            { num: 21, name: "高須 竜輝" },
            { num: 22, name: "竹ノ内 雄按" },
            { num: 23, name: "橘木 悠生" },
            { num: 24, name: "田中 ひまり" },
            { num: 25, name: "千田 直人" },
            { num: 26, name: "富田 真由" },
            { num: 27, name: "豊田 貴理恵" },
            { num: 28, name: "中島 美月" },
            { num: 29, name: "中村 倭人" },
            { num: 30, name: "西野 晴" },
            { num: 31, name: "長谷川 幸大" },
            { num: 32, name: "服部 未來" },
            { num: 33, name: "伏見 陽向" },
            { num: 34, name: "山口 晃平" },
            { num: 35, name: "山田 悠太朗" },
            { num: 36, name: "山本 琥太郎" },
            { num: 37, name: "山守 蒼悟" },
            { num: 38, name: "吉尾 芽菜" },
            { num: 39, name: "吉田 将" },
            { num: 40, name: "和田 菜歩" },
        ]
    },
    {
        year: 2026,
        class: "G2E",
        teacher: "中原 早苗",
        students:[
            { num: 1, name: "伊藤 有希" },
            { num: 2, name: "内丸 駿汰" },
            { num: 3, name: "加藤 璃桜" },
            { num: 4, name: "木下 陽生" },
            { num: 5, name: "庄 葵衣" },
            { num: 6, name: "園部 柚菜" },
            { num: 7, name: "髙久 真綾" },
            { num: 8, name: "田中 沙侑" },
            { num: 9, name: "田中 仁湖" },
            { num: 10, name: "坪井 椋哉" },
            { num: 11, name: "冨谷 智瑛里" },
            { num: 12, name: "野口 琉翔" },
            { num: 13, name: "前田 紗良" },
            { num: 14, name: "松田 奈々" },
            { num: 15, name: "松永 憲明" },
            { num: 16, name: "松野 玲旺" },
            { num: 17, name: "松濱 周" },
            { num: 18, name: "三村 蒼空" },
            { num: 19, name: "奥川 翼" },
            { num: 20, name: "小田 智駿" },
            { num: 21, name: "桂 蒼唯" },
            { num: 22, name: "川村 翔斗" },
            { num: 23, name: "木村 将大" },
            { num: 24, name: "桑山 瑛多" },
            { num: 25, name: "近藤 恵介" },
            { num: 26, name: "坂井田 真叶" },
            { num: 27, name: "谷口 倫太郎" },
            { num: 28,name: "長谷川 幸大" },
            { num: 29, name: "馬場 光平" },
            { num: 30, name: "村上 漣" },
            { num: 31, name: "森 柊介" },
            { num: 32, name: "吉田 将" },
            { num: 33, name: "渡邊 聖永" },
        ]
    },
    {
        year: 2026,
        class: "G2F",
        teacher: "岩永 英志",
        students:[
            { num: 1, name: "安藤 聡一" },
            { num: 2, name: "飯田 空翔" },
            { num: 3, name: "石黒 陽路" },
            { num: 4, name: "犬塚 涼介" },
            { num: 5, name: "井上 菜月" },
            { num: 6, name: "鵜飼 宗太郎" },
            { num: 7, name: "大森 龍幸" },
            { num: 8, name: "奥村 僚太" },
            { num: 9, name: "勝田 壮一郎" },
            { num: 10, name: "小池 凌太郎" },
            { num: 11, name: "小林 隼哉" },
            { num: 12, name: "小牧 璃子" },
            { num: 13, name: "酒井 蒼空" },
            { num: 14, name: "櫻井 瑛太" },
            { num: 15, name: "柴田 成" },
            { num: 16, name: "清水 咲良" },
            { num: 17, name: "杉原 悠衣" },
            { num: 18, name: "鈴置 亜麻" },
            { num: 19, name: "鈴木 康介" },
            { num: 20, name: "高田 佳那子" },
            { num: 21, name: "丹羽 春樹" },
            { num: 22, name: "萩原 逢人" },
            { num: 23, name: "長谷川 凌一" },
            { num: 24, name: "福本 蒼真" },
            { num: 25, name: "藤原 侑大" },
            { num: 26, name: "古田 絹乃" },
            { num: 27, name: "眞嶋 洋輔" },
            { num: 28, name: "三品 憧真" },
            { num: 29, name: "向 翔音天" },
            { num: 30, name: "村上 依吹" },
            { num: 31, name: "谷口 遼" },
            { num: 32, name: "山内 凛香" },
            { num: 33, name: "吉川 琥道" },
            { num: 34, name: "萬 悠佑" },
        ]
    },
    {
        year: 2026,
        class: "G2G",
        teacher: "坪井 しおり",
        students:[
            { num: 1, name: "足立 虎太朗" },
            { num: 2, name: "安部 光紀" },
            { num: 3, name: "飯山 仁子" },
            { num: 4, name: "伊藤 慶人" },
            { num: 5, name: "鵜飼 彩葉" },
            { num: 6, name: "加藤 煌大" },
            { num: 7, name: "加藤 大智" },
            { num: 8, name: "香田 彩" },
            { num: 9, name: "河野 結菜" },
            { num: 10, name: "小柏 瞬正" },
            { num: 11, name: "志水 更紗" },
            { num: 12, name: "杉江 宥虎" },
            { num: 13, name: "高須 竜輝" },
            { num: 14, name: "高橋 洸太" },
            { num: 15, name: "瀧 奏介" },
            { num: 16, name: "竹ノ内 雄按" },
            { num: 17, name: "谷口 連太郎" },
            { num: 18, name: "坪井 音和" },
            { num: 19, name: "戸崎 翔太" },
            { num: 20, name: "成瀬 清良" },
            { num: 21, name: "西野 晴喜" },
            { num: 22, name: "西原 悠仁" },
            { num: 23, name: "花井 亜純" },
            { num: 24, name: "林 勇乃心" },
            { num: 25, name: "日比 颯栄" },
            { num: 26, name: "福谷 美結" },
            { num: 27, name: "牧野 友哉" },
            { num: 28, name: "松原 翔太" },
            { num: 29, name: "宮崎 心結" },
            { num: 30, name: "宮脇 凛" },
            { num: 31, name: "山口 慶一郎" },
            { num: 32, name: "山口 巧真" },
            { num: 33, name: "吉田 隼斗" },
            { num: 34, name: "若松 奏佑" },
        ]
    },
    {
        year: 2026,
        class: "G2I",
        teacher: "伊藤 利紀",
        students:[
            { num: 1, name: "伊藤 明紗" },
            { num: 2, name: "小笠原 優花" },
            { num: 3, name: "尾山 柚月" },
            { num: 4, name: "加藤 蒼真" },
            { num: 5, name: "川上 夏希" },
            { num: 6, name: "丸山 蒼太" },
            { num: 7, name: "森田 智希" },
            { num: 8, name: "山田 桐也" },
            { num: 9, name: "渡邊 七海" },
            { num: 10, name: "伊垣 蒼空" },
            { num: 11, name: "石本 かのん" },
            { num: 12, name: "井上 胡桃" },
            { num: 13, name: "織田 琉希" },
            { num: 14, name: "國井 陸" },
            { num: 15, name: "河本 哲旺" },
            { num: 16, name: "小林 凛太郎" },
            { num: 17, name: "島 凛里花" },
            { num: 18, name: "島田 歩" },
            { num: 19, name: "杉本 茉夕" },
            { num: 20, name: "鈴木 幹太" },
            { num: 21, name: "鈴木 健太" },
            { num: 22, name: "竹内 夢花" },
            { num: 23, name: "田島 優太" },
            { num: 24, name: "田山 彩葉" },
            { num: 25, name: "塚田 里彩" },
            { num: 26, name: "坪井 望乃" },
            { num: 27, name: "徳田 太平" },
            { num: 28, name: "豊田 貴理恵" },
            { num: 29, name: "中村 優" },
            { num: 30, name: "生津 佑衣" },
            { num: 31, name: "野浦 晃司" },
            { num: 32, name: "東島 運央" },
            { num: 33, name: "日比野 醍伸" },
            { num: 34, name: "古川 夕真" },
            { num: 35, name: "牧原 雄翔" },
            { num: 36, name: "松原 香詠" },
            { num: 37, name: "水野 栞那" },
            { num: 38, name: "村瀬 舜" },
            { num: 39, name: "米津 華那" },
            { num: 40, name: "和田 菜歩" },
            { num: 41, name: "和田 優里菜" },
        ]
    },
    {
        year: 2026,
        class: "G2G",
        teacher: "竹内 勲",
        students:[
            { num: 1, name: "大橋 真綾" },
            { num: 2, name: "岡田 佳悟" },
            { num: 3, name: "松山 宗太郎" },
            { num: 4, name: "生駒 千明" },
            { num: 5, name: "奥村 優斗" },
            { num: 6, name: "上島 璃子" },
            { num: 7, name: "北嶋 琉衣" },
            { num: 8, name: "重藤 亜柚" },
            { num: 9, name: "武中 心瑠" },
            { num: 10, name: "土下 煌華" },
            { num: 11, name: "都築 志帆" },
            { num: 12, name: "中村 倭人" },
            { num: 13, name: "西部 瑛太" },
            { num: 14, name: "吉田 千咲" },
            { num: 15, name: "市原 亘" },
            { num: 16, name: "杉本 京介" },
            { num: 17, name: "鳥越 かれん" },
            { num: 18, name: "花井 香穂" },
            { num: 19, name: "松井 楓" },
            { num: 20, name: "生田 恭一郎" },
            { num: 21, name: "稲熊 香織" },
            { num: 22, name: "岩崎 飛向" },
            { num: 23, name: "上田 楓花" },
            { num: 24, name: "大栗 那優" },
            { num: 25, name: "大橋 柚斗" },
            { num: 26, name: "川口 碧惟" },
            { num: 27, name: "熊谷 元気" },
            { num: 28, name: "小梶 礼乃" },
            { num: 29, name: "小橋 俊哉" },
            { num: 30, name: "澁谷 陽歩" },
            { num: 31, name: "髙野 真幸" },
            { num: 32, name: "橘木 悠生" },
            { num: 33, name: "千田 直人" },
            { num: 34, name: "二谷 康太" },
            { num: 35, name: "根間 悠叶" },
            { num: 36, name: "平木 海叶" },
            { num: 37, name: "伏見 陽向" },
            { num: 38, name: "舩木 夢七" },
            { num: 39, name: "森 春乃" },
            { num: 40, name: "山口 晃平" },
            { num: 41, name: "依田 樹" },
        ]
    },
    {
        year: 2026,
        class: "T2A",
        teacher: "河合 忍",
        students:[
            { num: 1, name: "浅井 聖人" },
            { num: 2, name: "稲熊 朝陽" },
            { num: 3, name: "岩崎 琉斗" },
            { num: 4, name: "江本 千咲" },
            { num: 5, name: "大西 哉斗" },
            { num: 6, name: "小川 龍祐" },
            { num: 7, name: "刑部 獅音" },
            { num: 8, name: "川村 蒼" },
            { num: 9, name: "木場 優菜" },
            { num: 10, name: "近藤 紗衣" },
            { num: 11, name: "立松 快都" },
            { num: 12, name: "田中 佑妃乃" },
            { num: 13, name: "玉木 隼翔" },
            { num: 14, name: "寺岡 修人" },
            { num: 15, name: "富成 橙暉" },
            { num: 16, name: "中島 祐希" },
            { num: 17, name: "中根 さくら" },
            { num: 18, name: "中村 晋司郎" },
            { num: 19, name: "仲山 富康" },
            { num: 20, name: "野田 洸希" },
            { num: 21, name: "野田 陽丸" },
            { num: 22, name: "波多 叶聖" },
            { num: 23, name: "服部 隼和" },
            { num: 24, name: "馬場 瑞季" },
            { num: 25, name: "濱口 晴大朗" },
            { num: 26, name: "原田 幸実" },
            { num: 27, name: "伴 聡眞" },
            { num: 28, name: "万代 希乃花" },
            { num: 29, name: "樋口 颯太" },
            { num: 30, name: "姫嶋 煌太" },
            { num: 31, name: "松野 人和" },
            { num: 32, name: "水野 緋音" },
            { num: 33, name: "溝口 聖七" },
            { num: 34, name: "宮崎 翔真" },
            { num: 35, name: "宮崎 耀大" },
            { num: 36, name: "安井 にこ" },
            { num: 37, name: "山形 虎太郎" },
            { num: 38, name: "山下 遥士" },
            { num: 39, name: "山下 真" },
            { num: 40, name: "山田 茉那" },
        ]
    },
    {
        year: 2026,
        class: "T2B",
        teacher: "舟橋 雄一",
        students:[
            { num: 1, name: "荒川 久弥" },
            { num: 2, name: "有谷 勇人" },
            { num: 3, name: "安中 陸隼" },
            { num: 4, name: "池部 和希" },
            { num: 5, name: "池本 成寿" },
            { num: 6, name: "太田 陽喜" },
            { num: 7, name: "太田 優希" },
            { num: 8, name: "岡部 英錬" },
            { num: 9, name: "岡本 拓真" },
            { num: 10, name: "小木曽 太一" },
            { num: 11, name: "奥田 翔光" },
            { num: 12, name: "加藤 聡一" },
            { num: 13, name: "北川 太陽" },
            { num: 14, name: "小塚 哲聖" },
            { num: 15, name: "斉藤 克昌" },
            { num: 16, name: "櫻木 陽" },
            { num: 17, name: "鈴木 新汰" },
            { num: 18, name: "砂畑 冠太" },
            { num: 19, name: "高橋 蒼太郎" },
            { num: 20, name: "田島 詠斗" },
            { num: 21, name: "谷上 悠" },
            { num: 22, name: "地濃 累" },
            { num: 23, name: "中野 喜晴" },
            { num: 24, name: "並木 陽介" },
            { num: 25, name: "二星 凱" },
            { num: 26, name: "広瀬 真人" },
            { num: 27, name: "藤谷 理生" },
            { num: 28, name: "松下 航大" },
            { num: 29, name: "三崎 壱櫂" },
            { num: 30, name: "水谷 優" },
            { num: 31, name: "村田 丈二" },
            { num: 32, name: "元永 貴久" },
            { num: 33, name: "安江 文埜" },
        ]
    },
    {
        year: 2026,
        class: "T2C",
        teacher: "原田 恭輔",
        students:[
            { num: 1, name: "伊藤 奏太" },
            { num: 2, name: "稲垣 丈琉" },
            { num: 3, name: "宇野 雫月" },
            { num: 4, name: "大矢 脩瑛" },
            { num: 5, name: "加藤 風海" },
            { num: 6, name: "蟹江 柊也" },
            { num: 7, name: "川辺 照貴" },
            { num: 8, name: "河村 琥羽" },
            { num: 9, name: "川村 航輝" },
            { num: 10, name: "小出 悠雅" },
            { num: 11, name: "小林 理孔" },
            { num: 12, name: "佐藤 禅" },
            { num: 13, name: "澤木 詞音" },
            { num: 14, name: "澤野 遼" },
            { num: 15, name: "新庄 壮真" },
            { num: 16, name: "鈴木 康介" },
            { num: 17, name: "鈴木 蓮音" },
            { num: 18, name: "高田 悠生" },
            { num: 19, name: "高原 淳志" },
            { num: 20, name: "竹延 久志" },
            { num: 21, name: "土田 拓弥" },
            { num: 22, name: "中村 心" },
            { num: 23, name: "西村 友吾" },
            { num: 24, name: "長谷川 優斗" },
            { num: 25, name: "長谷川 怜央" },
            { num: 26, name: "蜂須賀 匠海" },
            { num: 27, name: "半田 怜大" },
            { num: 28, name: "前芝 宗汰" },
            { num: 29, name: "宮田 樹" },
            { num: 30, name: "山下 雄大" },
            { num: 31, name: "山田 章亜" },
            { num: 32, name: "山本 朔大" },
            { num: 33, name: "吉田 蒼空" },
        ]
    }
]